name: valotech
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #UI関連
  cupertino_icons: ^1.0.6
  bordered_text: ^2.0.0
  persistent_bottom_nav_bar: ^6.2.1

  #firebase関連
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.2
  cached_network_image: ^3.4.1
  path_provider: ^2.1.4

  #スプラッシュ
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/map/
    - assets/images/character/

#スプラッシュ
flutter_native_splash:
  color: "#202124"
  image: assets/images/icon/Valotech_icon.png